### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by Philo** [Philo/cake-gulp#1]

**Comment by nengberg** [comment]
I think we might be able to apply my implementation for cake-npm in this repository as well. What do you think?

**Comment by Philo** [comment]
Absolutely, they are very similar.

 Apologies I haven'tgotten back to  you earlier, I'll be  without internetaccess for the weekend but feel free to submit a similar  pull  requestfor adding unit tests here

**Comment by nengberg** [comment]
Will do if I got the time!
