### ISSUE TITLE
Cake Gulp needs to reference Cake.Core 0.22.0

### ISSUE THREAD

**Issue by tidusjar** [Philo/cake-gulp#16]
See error below:

> Cake.exe : Error: Cake.Core.CakeException: The assembly 'Cake.Gulp, Version=0.7.1.0, Culture=neutral, PublicKeyToken=null' 
> At line:1 char:1
>  & "C:\projects\requestplex\tools\Cake\Cake.exe" "build.cake" -target= ...
>  
>    CategoryInfo          : NotSpecified: (Error: Cake.Cor...KeyToken=null' :String) [], RemoteException
>    FullyQualifiedErrorId : NativeCommandError
>  
> is referencing an older version of Cake.Core (0.17.0). 
> This assembly need to reference at least Cake.Core version 0.22.0. 
> Another option is to do
> wngrade Cake to an earlier version. 
> It's not recommended, but you can explicitly opt-out of assembly verification 
> by configuring the Skip Verification setting to true
> (i.e. command line parameter "--settings_skipverification=true", 
> envrionment variable "CAKE_SETTINGS_SKIPVERIFICATION=true", 
> read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
>    at Cake.Core.Reflection.AssemblyVerifier.Verify(Assembly assembly)
>    at Cake.Core.Reflection.AssemblyLoader.Load(FilePath path, Boolean verify)
>    at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
>    at Cake.Commands.BuildCommand.Execute(CakeOptions options)
>    at Cake.CakeApplication.Run(CakeOptions options)
>    at Cake.Program.Main()
> Command executed with exc

I was able to work around this by using the `--settings_skipverification=true` argument like the error states. But thought you'd need to know this :)

**Comment by bohms27** [comment]
Curious if Cake.Git, Cake.Kudu, Cake.Powershell and Cake.Json will have the same issues. Cake.npm had it but was just updated.

**Comment by gep13** [comment]
@bohms27 all addins will have this until updated with todays release of Cake. See the release blog post for more information. Recommendation is to pin to a specific version of Cake, I.e. 0.21.1.

**Comment by Philo** [comment]
I'm planning to look at updating gulp tomorrow requires a bit more work to support netstandard and net46, all being well it should be available tomorrow
