### ISSUE TITLE
Target .NET Standard 2.0

### ISSUE THREAD

**Issue by pascalberger** [Philo/cake-gulp#24]
Target .NET Standard 2.0

**Comment by theramis** [comment]
Hey @pascalberger, did you want the nuget package to target just .net standard 2.0 or would you like to keep the target to .net46?

**Comment by pascalberger** [comment]
@theramis With the recent discussions multi-targetting is again the way to go, as .NET Standard has issues while running on anything lower than full framework 4.7.2. As Cake itself requires 4.6.1 we can multi-target to 4.6.1 and .NET Standard 2.0
