### ISSUE TITLE
Global grunt exeuction does not evaluate arguments

### ISSUE THREAD

**Issue by nengberg** [Philo/cake-gulp#3]
Hi,

Nice to see a plugin for Gulp! :+1: 

I found out that the global execution of grunt did not evaluate arguments as the local one did.
I forked your repository and added the evaluation and then I was able to specify a path to my gulpfile and everything worked as expected.

Here is my fix: https://github.com/nengberg/cake-gulp/commit/15b9f9b0d041f61371eed26cc92baea0337c0b24

Am I correct or is there another way in solving this? Otherwise, would you like me to open a pull request for this one?

Best Regards
NIklas

**Comment by Philo** [comment]
Thanks @nengberg,

Please open the pull request and i'll merge that asap.

Apologies for the delay in replying

**Comment by Philo** [comment]
I need to push a new version to nuget so fixed this en-route.  Thanks for spotting it
